spring:
  application:
    name: stream-service
  #rabbitmq连接字符串
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 60000

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

