spring:
  application:
    name: stream-service
  #rabbitmq连接字符串
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      #延迟队列
      rabbit:
        #默认全局开启requeue
#        listener:
#          defalut-requeue-rejected: true
        bindings:
          #死信队列配置
          dlq-consumer:
            consumer:
              #开启死信队列（默认topic.dlq）
              auto-bind-dlq: true
          delayed-producer:
            producer:
              delayed-exchange: true
          #仅仅对当前的requeue-consumer，开启requeue
          requeue-consumer:
            group: requeue-group
            consumer:
              requeueRejected: true
      #当前消费者的实例总量
      instanceCount: 2
      #最大值instanceCount-1，当前实例的索引号
      instanceIndex: 0
      bindings:
        #绑定channel到broadcast
        myTopicConsumer:
          destination: broadcast
        myTopicProducer:
          destination: broadcast
        #消息分组
        GroupTopicConsumer:
          destination: group-topic
          group: groupA
          #打开分区功能
          cosumer:
            partitioned: true
        GroupTopicProducer:
          destination: group-topic
          producer:
            #两个消费分区
            partition-count: 2
            # spel表达式（key resolver）
            #只有索引参数为1的节点（消费者 ），才能消费消息
            partition-key-expression: 1
        #延迟消息配置
        delayed-consumer:
          destination: delayed-topic
        delayed-producer:
          destination: delayed-topic
        #异常重试单机消息配置
        error-consumer:
          destination: error-out-topic
          consumer:
            #重试次数
            #次数等于1表示不重试
            max-attempts: 1 #1是避免跟requeue的重试冲突
        error-producer:
          destination: error-out-topic
        # requeue重试
        requeue-consumer:
          destination: requeue-topic
        requeue-producer:
          destination: requeue-topic
        #死信队列配置
        dlq-consumer:
          destination: dlq-topic
          group: dlq-group
          consumer:
            max-attempts: 2
        dlq-producer:
          destination: dlq-topic
        #降级的配置
        fallback-consumer:
          destination: fallback-topic
          group: fallback-group
          consumer:
            max-attempts: 2
        fallback-producer:
          destination: fallback-topic
        # input channel: fallback-topic.fallback-group.errors

server:
  port: 60000

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

