server:
  port: 20003

spring:
  application:
    name: sleuthA
  sleuth:
    sampler:
      probability: 1
  #zipkin的地址
  zipkin:
    base-url: http://localhost:30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka

info:
  app:
    name: sleuthA
    description: test

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file: ${spring.application.name}.log

